import turtle
a= input("집의 크기를 입력하세요 :")
a = int(a)
t=turtle.Turtle()
t.forward(a)
t.left(90)
t.forward(a)
t.left(90)
t.forward(a)
t.left(90)
t.forward(a)
t.left(180)
t.forward(a)
t.right(120)
t.forward(a)
t.right(120)
t.forward(a)
t.right(120)
turtle.done()